### ISSUE TITLE
Support "plainText"/"txt" language

### ISSUE THREAD

**Issue by Hurtak** [rexxars/react-refractor#23]
Hey, It would be great if `react-refractor` supported `plainText` or `txt` language settings (or if the language prop was optional) that would do no highlight.

Use case: I have a react-refractor component for code highlight in my blog, and sometimes it is just some pseudocode that I do not want any highlight rules applied to, but I want the code block to have the same styles as other code blocks.

Related https://github.com/wooorm/refractor/issues/49

**Comment by rexxars** [comment]
Implemented a `plainText` option in [v3.1.0](https://github.com/rexxars/react-refractor/releases/tag/v3.1.0)
