### ISSUE TITLE
Update refractor to v4?

### ISSUE THREAD

**Issue by karlhorky** [rexxars/react-refractor#24]
Hi there, first of all, thanks for this package, really nice!

There are some nice new features in `refractor@4.1.0` (features from Prism), such as [SQL tagged template strings with JavaScript](https://github.com/wooorm/refractor/issues/47)

Would it be possible to upgrade to `refractor` v4?

Original feature implemented in Prism: https://github.com/PrismJS/prism/pull/2945

**Comment by ruler501** [comment]
There's a security warning for the version of prismjs that refractor 3.x requires so it is important to upgrade to 4.x as soon as possible.

**Comment by sunknudsen** [comment]
My gut feeling is that package will have to be refactored to ESM before update is possible. 😔

**Comment by karlhorky** [comment]
There are ways to get around this, to import an ESM package in a CJS package.

But yeah, switching to ESM would be a bit easier.

**Comment by sunknudsen** [comment]
@karlhorky Would you happen to know how to update underlying prismjs package?

**Comment by karlhorky** [comment]
Not sure I'm understanding - are you still talking about ESM and `refractor`? Or something else now?

**Comment by rexxars** [comment]
As of [v3.0.0](https://github.com/rexxars/react-refractor/releases/tag/v3.0.0), this module now uses refractor 4. As @sunknudsen points out, this required a refactor to an ESM-only package.

**Comment by karlhorky** [comment]
Thanks @rexxars, amazing!
